# .rubocop.yml

Style/MixinUsage:
  Exclude:
    - 'bin/update'
    - 'bin/setup'
Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'db/schema.rb'
Style/StringLiterals: 
  Exclude:
    - 'db/schema.rb'
Style/NumericLiterals:
  Exclude:
    - 'db/schema.rb'
Style/FrozenStringLiteralComment:
  Exclude:
    - 'db/schema.rb'
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Enabled: false